### ISSUE TITLE
Profiles bootstrap

### ISSUE THREAD

**Issue by pvoborni** [modularity-modules/freeipa#3]
Hi,

was looking at https://src.fedoraproject.org/modules/freeipa/c/6d22cb66fc2588929278e4b9585b59e809615f98?branch=4.6

There is a draft for some initial profiles.  To be honest, I don't understand profiles much, so might be be off here.

I will assume that:

- profile is created for certain use case
- only top level packages should be listed there (i.e. not their dependencies)

The commit above specifies:

```
    profiles:
        default:
            description: A generated profile based on top-lvl package list.
            rpms:
                - freeipa-client
                - freeipa-client-common
                - freeipa-common
                - freeipa-desktop-profile
                - freeipa-python-compat
                - freeipa-server
                - freeipa-server-common
                - freeipa-server-dns
                - freeipa-server-trust-ad
        client:
            description: FreeIPA Client
            rpms:
                - freeipa-client
                - freeipa-client-common
                - freeipa-common
        domaincontroller:
            description: FreeIPA Domain Controller
            rpms:
                - freeipa-common
                - ntp
                - bind-dyndb-ldap
                - certmonger
        dnsserver:
            description: FreeIPA DNS Server
            rpms:
                - freeipa-common
                - freeipa-server-dns
        activedirectory:
            description: FreeIPA Integration with Active Directory
            rpms:
                - freeipa-common
                - freeipa-server-trust-ad
```

I'd suggest to change it into:
```       
       default:
            description:  FreeIPA Domain Controller with DNS server and Active Directory support
            rpms:
                - freeipa-server-dns
                - freeipa-server-trust-ad
        client:
            description: FreeIPA Client
            rpms:
                - freeipa-client
       domaincontroller:
            description: Minimal FreeIPA Domain Controller
            rpms:
                - freeipa-server
        dnsserver:
            description: FreeIPA Domain Controller with DNS Server
            rpms:
                - freeipa-server-dns
        activedirectory:
            description: FreeIPA Domain Controller with Active Directory trust support
            rpms:
                - freeipa-server-trust-ad
```

Notes:
* `freeipa-server-trust-ad` requires `freeipa-server` and `bind-dyndb-ldap` (which is good only for dns)
* `freeipa-server-dns` requires `freeipa-server`
* `freeipa-common` is a dependence for the rest, no need to specify it
* I removed `freeipa-desktop-profile` from default as it is an optional component which provides integration with Fleet Commander and most people won't probably want it
* I'm not sure about  using Domain Controller there.
